wandb_version: 1

device:
  desc: null
  value: cpu
env:
  desc: null
  value: reacher
seed:
  desc: null
  value: 0
eval_freq:
  desc: null
  value: 100
max_epochs:
  desc: null
  value: 12000
checkpoints_path:
  desc: null
  value: null
load_model:
  desc: null
  value: ''
batch_size:
  desc: null
  value: 256
num_eval_batch:
  desc: null
  value: 100
data_size:
  desc: null
  value: 1000
normalize:
  desc: null
  value: none
arch:
  desc: null
  value: 256-R-256-R-256-R|T
optimizer:
  desc: null
  value: sgd
regularization:
  desc: null
  value: none
dropout_probability:
  desc: null
  value: 0.5
lamH:
  desc: null
  value: -1
lamW:
  desc: null
  value: 0.01
lr:
  desc: null
  value: 0.01
mode:
  desc: null
  value: 'null'
data_folder:
  desc: null
  value: ./dataset/mujoco
project:
  desc: null
  value: NC_explore
group:
  desc: null
  value: reg-none
name:
  desc: null
  value: Ereacher_DS1000_wd0.01_Eps12000_Reg-none
_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1720513155
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 13
      - 14
      - 16
      - 23
      4: 3.9.19
      5: 0.17.3
      8:
      - 5
      10:
      - 3
      13: linux-x86_64
    visualize:
      NRC3_vs_gamma:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/line/v0
          fieldSettings:
            x: gamma
            y: NRC3
            stroke: null
          stringSettings:
            title: NRC3_vs_gamma
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: NRC3_vs_gamma_table
                fields: []
      NRC3_vs_epoch:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/line/v0
          fieldSettings:
            x: epoch
            y: NRC3
            stroke: null
          stringSettings:
            title: NRC3_vs_epoch
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: NRC3_vs_epoch_table
                fields: []
